backend:
  name: git-gateway
  repo: christos-kostopoulos/altour
  branch: main
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  # Main Pages EN
  - name: "mainPageEn"
    label: "Main Pages (english)"
    filter: { field: language, value: en }
    identifier_field: name
    editor:
      preview: true
    files:
      #Index
      - file: "content/en/main-pages/index.md"
        label: Index
        name: indexEN
        identifier_field: name
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: templates/index,
            }
          - { label: Type, name: type, widget: hidden, default: 1 }
          - { label: Language, name: language, widget: hidden, default: en }
          - { label: Hero Heading, name: heroHeading, widget: string }
          - { label: Hero Image, name: image, widget: image }
          - { label: Project Title, name: projectHeading, widget: string }
          - {
              label: Project Description,
              name: projectDescription,
              widget: text,
            }
          - {
              label: Locations,
              name: locations,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Latest,
              name: latest,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
      #About
      - file: "content/en/main-pages/about.md"
        label: About
        name: aboutEN
        filter: { field: language, value: en }
        identifier_field: name
        editor:
          preview: true
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about",
            }
          - { label: Image, name: image, widget: image }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Image, name: image1, widget: image },
                  { label: "Body", name: "body", widget: "markdown" },
                ],
            }
          - {
              label: Greek Ministry,
              name: sectionMinistry,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Thermal Springs,
              name: thermalSprings,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Goals,
              name: goals,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Sustainable,
              name: sustainable,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Body, name: body, widget: markdown },
                ],
            }

          #Locations ana applying areas
      - file: "content/en/main-pages/locations.md"
        label: Locations
        name: locationsEN
        identifier_field: name
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: templates/locations,
            }
          - { label: Type, name: type, widget: hidden, default: 1 }
          - { label: Language, name: language, widget: hidden, default: en }
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }

  #Location EN
  - name: "locationEn"
    label: "Location (english)"
    folder: "content/en/location"
    filter: { field: contentType, value: location }
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: templates/location,
        }
      - { label: Slug, name: slug, widget: string }
      - { label: Language, name: language, widget: hidden, default: en }
      - {
          label: Content Type,
          name: contentType,
          widget: hidden,
          default: location,
        }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - {
          label: Title,
          name: title,
          widget: string,
          pattern: [".{0,80}", "Oopsy, no more that 80 characters"],
        }
      - {
          label: Body,
          name: body,
          widget: markdown,
          default: "Be interesting but not annoying",
        }
      - {
          label: Date,
          name: date,
          widget: date,
          format: YYYY-MM-DD,
          default: "",
        }

  - name: "upcomingEn"
    label: "Upcoming (english)"
    folder: "content/en/upcoming"
    filter: { field: contentType, value: upcoming }
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: templates/upcoming,
        }
      - { label: Slug, name: slug, widget: string }
      - { label: Language, name: language, widget: hidden, default: en }
      - {
          label: Content Type,
          name: contentType,
          widget: hidden,
          default: upcoming,
        }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - {
          label: Title,
          name: title,
          widget: string,
          pattern: [".{0,80}", "Oopsy, no more that 80 characters"],
        }
      - {
          label: Description,
          name: description,
          widget: string,
          default: [".{0,80}", "Oopsy, no more that 80 characters"],
        }
      - {
          label: Body,
          name: body,
          widget: markdown,
          default: "Be interesting but not annoying",
        }
      - {
          label: Date,
          name: date,
          widget: date,
          format: YYYY-MM-DD,
          default: "",
        }
  #----------------------------------------------gr

  # Main Pages gr
  - name: "mainPageGr"
    identifier_field: name
    label: "Main Pages (Greek)"
    filter: { field: language, value: gr }

    editor:
      preview: true
    files:
      #Home
      - file: "content/gr/main-pages/index.md"
        label: Index
        name: indexGR
        identifier_field: name
        fields:
          - { label: Template Key, name: templateKey, widget: hidden }
          - { label: Type, name: type, widget: hidden, default: 1 }
          - { label: Language, name: language, widget: hidden, default: gr }
          - { label: Hero Heading, name: heroHeading, widget: string }
          - { label: Hero Image, name: image, widget: image }
          - { label: Project Title, name: projectHeading, widget: string }
          - {
              label: Project Description,
              name: projectDescription,
              widget: text,
            }
          - {
              label: Locations,
              name: locations,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Latest,
              name: latest,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
      #About Page
      - file: "content/gr/main-pages/about.md"
        label: "About"
        name: "aboutGR"
        filter: { field: language, value: gr }
        identifier_field: name
        editor:
          preview: true
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about",
            }
          - { label: Image, name: image, widget: image }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Greek Ministry,
              name: sectionMinistry,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Image, name: image, widget: image },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Thermal Springs,
              name: thermalSprings,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Goals,
              name: goals,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Body, name: body, widget: markdown },
                ],
            }
          - {
              label: Sustainable,
              name: sustainable,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Body, name: body, widget: markdown },
                ],
            }

        #Locations ana applying areas
      - file: "content/gr/main-pages/locations.md"
        label: Locations
        name: locationsGR
        identifier_field: name
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: templates/locations,
            }
          - { label: Type, name: type, widget: hidden, default: 1 }
          - { label: Language, name: language, widget: hidden, default: gr }
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }

  #Location gr
  - name: "locationGr"
    label: "Location (Greek)"
    folder: "content/gr/location"
    filter: { field: contentType, value: location }
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: templates/location,
        }
      - { label: Slug, name: slug, widget: string }
      - { label: Language, name: language, widget: hidden, default: gr }
      - {
          label: Content Type,
          name: contentType,
          widget: hidden,
          default: location,
        }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - {
          label: Title,
          name: title,
          widget: string,
          pattern: [".{0,80}", "Oopsy, no more that 80 characters"],
        }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Date,
          name: date,
          widget: date,
          format: YYYY-MM-DD,
          default: "",
        }

  - name: "upcomingGr"
    label: "Upcoming (Greeek)"
    folder: "content/gr/upcoming"
    filter: { field: contentType, value: upcoming }
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: templates/upcoming,
        }
      - { label: Slug, name: slug, widget: string }
      - { label: Language, name: language, widget: hidden, default: gr }
      - {
          label: Content Type,
          name: contentType,
          widget: hidden,
          default: upcoming,
        }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - {
          label: Title,
          name: title,
          widget: string,
          pattern: [".{0,80}", "Oopsy, no more that 80 characters"],
        }
      - {
          label: Body,
          name: body,
          widget: markdown,
          default: "Be interesting but not annoying",
        }
      - {
          label: Description,
          name: description,
          widget: string,
          default: [".{0,80}", "Oopsy, no more that 80 characters"],
        }
      - {
          label: Date,
          name: date,
          widget: date,
          format: YYYY-MM-DD,
          default: "",
        }
